### ISSUE TITLE
Do we still need "imagemargin"?

### ISSUE THREAD

**Issue by christianbarkowsky** [ErdmannFreunde/euf_portfolio#32]
That is unnecessary @denniserdmann 

<img width="1307" alt="Bildschirmfoto 2023-07-31 um 10 29 50" src="https://github.com/erdmannfreunde/contao-portfolio-bundle/assets/1230547/1df76406-4767-4f01-bca7-3e49ef688904">

**Comment by denniserdmann** [comment]
No, we don't need this anymore
