### ISSUE TITLE
Unveröffentlichte Einträge werden trotzdem angezeigt

### ISSUE THREAD

**Issue by raukm** [ErdmannFreunde/euf_portfolio#34]
Ich habe eine Installaton von Contao 4.13 auf Contao 5.3 aktualisiert.
Die Erweiterung funktioniert da eigentlich ganz gut, allerdings werden auch Portfolioeinträge, die noch nicht veröffentlicht, im Frontend ausgegeben.

**Comment by denniserdmann** [comment]
Ich kann das Verhalten bestätigen, allerdings nur, wenn das unveröffentliche Element zusätzlich hervorgehoben (Stern-Icon) ist. Wir werden uns darum kümmern.

**Comment by jedoCodes** [comment]
ich kann das auch bestätigen, selbst ohne featured (stern). Es ist genau so, das in der liste alle angezeigt werden, bei den unveröffentlichten, kommt beim klicken auf den link eine 404

Konnte es auf die "findPublishedByPids" Funktion eingrenzen. Bei mir wurden nur alle veröffentlichten anzeigt, wenn alles was innerhalb "if ($arrCategoeries)" ignoriert wurde.

Ich habe das mal zu Testzwecken bei mir wie folgt abgeändert und es scheint zu funktionieren

PortfolioModel  -> findPublishedByPids

```
        if (!empty($arrCategories)) {

            $categoriesArray = is_array($arrCategories) ? $arrCategories : StringUtil::deserialize($arrCategories, true);
            
            $categoryConditions = [];

            // Iterieren durch jede Kategorie im Array
            foreach ($categoriesArray as $category) {
                // Füge der Bedingung das LIKE-Kriterium für jede Kategorie hinzu
                $categoryCondition = "'%\"$category\"%'";
                $categoryConditions[] = "$t.categories LIKE $categoryCondition";
            }
            $categoryCondition = implode(" OR ", $categoryConditions);

            // Fügen die kombinierte Bedingung zu Ihrem $arrColumns hinzu
            $arrColumns[] = "($categoryCondition)";
        }
```

keine Ahnung ob das mit den Filtern funktioniert, aber ist der Liste werden somit nur alle veröffentlichten angezeigt.

**Comment by Shoekrates** [comment]
Ich möchte hier nochmal einhaken und muss leider bestätigen, dass unveröffentlichte Elemente unabhängig vom Zustand „Hervorgehoben“ immer angezeigt werden.
Der Fix von @jedoCodes hat leider nicht geholfen.
Contao 5.3.9, PHP 8.1, Portfolio 5.0.1

**Comment by denniserdmann** [comment]
Sollte in Version 5.0.2 behoben sein

**Comment by Shoekrates** [comment]
Kann ich bestätigen, deaktivierte Elemente werden jetzt nicht mehr angezeigt. Danke!
