### ISSUE TITLE
Bildergrössen werden nicht übernommen

### ISSUE THREAD

**Issue by krypta83** [ErdmannFreunde/euf_portfolio#35]
Ich habe eine Contao 5.3.7-Installation im Einsatz.
Jedoch werden bei den Templates die vordefinierten Bildergrössen nicht übernommen. Es wird jeweils immer das Bild in ganzer Grösse eingebunden.

Beispiel:
[https://neu.krall.ch/Home](url)

**Comment by denniserdmann** [comment]
Du meinst die Bildgröße im Portfolio-Item, richtig? Denn wenn ich eine Bildgröße im Frontend-Modul vergebe, wird diese auch berücksichtigt. Beispiel: https://lasr-4.contao-theme.de/referenzen.html

**Comment by krypta83** [comment]
Alles klar. 
Sorry, ich muss die Bildeinstellungen im Frontendmodul vergeben. Ich habe dies vergessen, bzw. die Bildeinstellungen jeweils pro Referenz festgelegt. Danke!

**Comment by denniserdmann** [comment]
Der Fehler ist aber berechtigt. Es sollte schon möglich sein, pro Rereferenz-Objekt eine Bildgröße anzugeben. Ich muss mir das bei Gelegenheit mal genauer ansehen und auch welche Einstellung bevorzugt behandelt werden soll, wenn sowohl in der Referenz, als auch im FE-Modul eine Bildgröße hinterlegt ist.

**Comment by denniserdmann** [comment]
Bildgrößen sollten nun auch pro Element einstellbar sein, werden allerdings vom Frontend-Modul überschrieben, sollte dort ebenfalls eine Größe hinterlegt sein.
